[tool.poetry]
name = "aoc2024"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygyat = "^1.0.6b0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
